<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BistroStarsHollow.Web.Admin</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BistroStarsHollow.Application\BistroStarsHollow.Application.csproj" />
    <ProjectReference Include="..\BistroStarsHollow.Infrastructure\BistroStarsHollow.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\SharedResource.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>

</Project>
